# Generated by Django 4.2.27 on 2026-01-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada'), ('no_show', 'No presentado')], default='pending', max_length=20)),
                ('tipo', models.JSONField(default=dict, help_text='Service type info: {id, nombre, categoria}')),
                ('participantes', models.JSONField(default=list, help_text='Participants list')),
                ('usuario_id', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_original', models.TextField(blank=True, null=True)),
                ('notas', models.JSONField(default=dict, help_text='Notes: {cliente, interna}')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
    ]
